### ISSUE TITLE
How do I modify the httpd.conf for apache?

### ISSUE THREAD

**Issue by superpan** [GrahamDumpleton/mod_wsgi-docker#14]
Hi there, I am trying to figure out how to modify the httpd.conf used by the container, or override it with a custom config file.

**Comment by GrahamDumpleton** [comment]
What sort of changes do you want to make?

The whole point of mod_wsgi-express is that it takes over configuration for you because so it is done in the best way for host a Python web application.

There is an ability to add additional configuration at the end of the generated configuration file by including the configuration file snippet in your code and using the `--include-file` option to `mod_wsgi-express`. There is also a special option `--rewrite-rules` which does a similar thing but which should only include rewrite rules, which need to be included in a quite specific spot in the generated configuration.

Would prefer that you explain first what you are trying to do. Where it is a common or useful thing I will expand what `mod_wsgi-express` does.

**Comment by superpan** [comment]
Thanks for your quick response @GrahamDumpleton .  I found some of your discussions on google groups and have figure out the solution using --include-file.  Thanks again.
