### ISSUE TITLE
docker hub fails with non-onbuild versions

### ISSUE THREAD

**Issue by jayenashar** [GrahamDumpleton/mod_wsgi-docker#19]
https://hub.docker.com/r/grahamdumpleton/mod-wsgi-docker/builds/

I'm trying to "inline" the onbuild version and use `grahamdumpleton/mod-wsgi-docker:python-3.4` directly.  The reason for doing this is so that `COPY . /app` is done as late as possible to make better use of the docker cache.  But it's failing because `libmysqlclient-dev` isn't installed.  I suspect it is using an old version of `grahamdumpleton/mod-wsgi-docker:python-3.4` which is because docker hub can't build these non-onbuild versions.

**Comment by GrahamDumpleton** [comment]
The problem is that for some real libmysqlclient-dev was only added to the Python 2.7 images.

Automated builds have been broken on Docker Hub for quite a while, this being the fault of Docker Hub, which is blocking ability to run ``setcap`` program even though they recommend using it in their own documentation.

As a result I have been manually building images on Carina Docker system from Rackspace. They are about to shut that down in a few days. I will try and get rebuilt images up. If I can't manage that, not sure how I will be able to update the images as I can't push them from my home network as my Internet speed is too slow.

**Comment by GrahamDumpleton** [comment]
Actually, that isn't true. The libmysqlclient-dev library should be in all of them.

**Comment by GrahamDumpleton** [comment]
Try again now after pulling latest images.

I may have to try and do it one more time as I suspect I know why it hadn't used correct base image. This is due to a flaw in Carina from Rackspace where if it does the build of an image on different node, it will use base image from Docker Hub rather than what you just built. So will probably need to build base image, push, then build derived image and push. If build base and derived image and then only push, could use older base image. Not more time to try that today though.

**Comment by jayenashar** [comment]
works for me!  in the future, could i build and push an image for you?

**Comment by GrahamDumpleton** [comment]
I have a new set of images I have been developing which supersede these images. The newer images don't use techniques which Docker recommends in their documentation, yet then bans you from using with automated builds. They will continue to work fine with automated builds.
