### ISSUE TITLE
Git not available

### ISSUE THREAD

**Issue by aop** [GrahamDumpleton/mod_wsgi-docker#5]
Trying to build python 2.7-onbuild causes this error:
Error [Errno 2] No such file or directory while executing command git clone -q git://github.com/mongodb/mongo-python-driver.git /app/.whiskey/tmp/pymongo
Cannot find command 'git'

**Comment by GrahamDumpleton** [comment]
Where are you trying to use 'git'?

Is this due to a git repository being mentioned inside of the requirements.txt file as source for Python package, or are you providing a action hooks script in which you are then running git.

The way the image is setup git is not installed by default. It should though be installed automatically if it is detected that a git repository is mentioned inside of the requirements.txt file thus requiring it to be installed.

If however you are trying to run git yourself from one of the action hooks scripts, it would necessary in the pre-build hook to install git first.

So let me know where it is being used from and can indicate better where you should put the lines to install the git package.

**Comment by GrahamDumpleton** [comment]
No response so closing.
