### ISSUE TITLE
Update to latest mod_wsgi

### ISSUE THREAD

**Issue by gsingers** [GrahamDumpleton/mod_wsgi-docker#8]
Any chance we can get this updated to the latest mod_wsgi?

**Comment by GrahamDumpleton** [comment]
As interim measure, add to your `requirements.txt` file:

```
mod_wsgi==4.5.2
```

This should from memory cause the newer version to be installed and replace existing version in image.

I am having problems with updating the images on Docker Hub at the moment because Docker Hub has broken automated builds, in as much as they now longer allow you to build images that want to use Linux capabilities. This appears to be a bug in Docker support for whatever file system type they are using on the build systems. This problem was occurring on and off for a while but now appears to be permanently broken. The only solution I have is to sign up for some separate CI/CD system which Docker build capabilities and build images there and push to Docker Hub. I can't push images from home as I down have the upload bandwidth.

As more permanent solution I am working on much better new Docker images that will not use port 80 and so not be dependent on needing Linux capabilities. These aren't exactly compatible and may need changes in how you use existing ones to change. The only other thing I can do is create an interim Docker image which is same as original but, just changes port 80 to port 8080 and make it available under a different name. You would still need to at least change the port number being exposed.

Can you tell me how you are using the images? Are you using just the base image or are you using the onbuild image? In the final replacement there likely will be no onbuild images as they have various limitations and best avoided.

**Comment by gsingers** [comment]
I'm using the onbuild.  Dockerfile is at https://github.com/lucidworks/searchhub/blob/master/python/Dockerfile

I'm currently running it on port 80.

**Comment by GrahamDumpleton** [comment]
This is still not tracking the very latest mod_wsgi version as only updated if feel necessary, but it was at least updated to 4.5.2 some time back. Closing this issue for now.
