### ISSUE TITLE
Updating the App

### ISSUE THREAD

**Issue by gsingers** [GrahamDumpleton/mod_wsgi-docker#9]
I now have this container working nicely with my Flask application, so thanks for saving me a bunch of time!

I'm wondering if there is an easy recipe for updating the container w/ a new version of the app without having to recreate the image?  Is it simply a matter of scp'ing the necessary bits up into the /app directory on the container?  Any docs would be most appreciated.

**Comment by GrahamDumpleton** [comment]
Sorry for the delayed reply. Have found a bunch of emails from back when I was on an extended overseas trip that never seemed to see.

Technically you could run the container but create a shell, then copy in or make the changes, plus run `mod_wsgi-docker-build` if there are changes to packages which are required. Then exit the container and use `docker commit` to convert the stopped container into an image. This will create a new layer on top of existing image with changes. Because it is a new layer, your container will keep growing fatter each time.

Personally is is probably just as easy to do a rebuild.
